#!/usr/bin/env node

const { Client } = require('pg');
require('dotenv').config();

const client = new Client({
  host: process.env.DB_HOST || 'localhost',
  port: process.env.DB_PORT || 5432,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
});

async function checkSEO() {
  try {
    await client.connect();
    console.log('Connected to database\n');

    const result = await client.query('SELECT value FROM settings WHERE namespace = $1', ['seo']);
    const seo = result.rows[0]?.value || { pages: [] };
    
    const allPages = seo.pages || [];
    const staticPages = allPages.filter(p => !(p.autoGenerated === true && p.path?.startsWith('/products/')));
    const productPages = allPages.filter(p => p.autoGenerated === true && p.path?.startsWith('/products/'));
    
    console.log('=== SEO Settings Summary ===');
    console.log(`Total pages: ${allPages.length}`);
    console.log(`Static pages: ${staticPages.length}`);
    console.log(`Product pages: ${productPages.length}`);
    console.log('');
    
    console.log('=== Static Pages (should NOT be deleted) ===');
    if (staticPages.length === 0) {
      console.log('⚠️  WARNING: No static pages found!');
    } else {
      staticPages.forEach(p => {
        console.log(`  ✓ ${p.path} (${p.autoGenerated === true ? 'auto' : p.autoGenerated === false ? 'custom' : 'no flag'})`);
      });
    }
    console.log('');
    
    console.log('=== Product Pages (auto-generated) ===');
    if (productPages.length === 0) {
      console.log('  (none)');
    } else {
      productPages.slice(0, 10).forEach(p => {
        console.log(`  - ${p.path}`);
      });
      if (productPages.length > 10) {
        console.log(`  ... and ${productPages.length - 10} more`);
      }
    }
    
    await client.end();
  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
}

checkSEO();
