import { Request, Response } from 'express';
import sequelize from '../../config/database';
import { QueryTypes } from 'sequelize';

const DEFAULTS = {
  seo: {
    home: { 
      title: 'Banyco', 
      description: '', 
      ogImage: '', 
      slug: '/' 
    },
    pages: [],
  },
};

/**
 * Get page metadata from CMS Settings
 * Supports both static pages (/products, /about) and dynamic pages (/posts/slug, /products/slug)
 */
export const getPageMetadata = async (req: Request, res: Response) => {
  try {
    let { path } = req.params;
    
    // Special debug endpoint
    if (path === '-debug-all') {
      const row = await sequelize.query(
        'SELECT value FROM settings WHERE namespace = :ns',
        {
          type: QueryTypes.SELECT,
          replacements: { ns: 'seo' },
        }
      ) as any[];
      const seoSettings = row?.[0]?.value || { pages: [] };
      return res.json(seoSettings);
    }
    
    // 1. Normalize path - ensure it starts with /
    // Express route gives us path without leading slash (e.g., "about" not "/about")
    if (!path.startsWith('/')) {
      path = '/' + path;
    }
    
    // Remove query params (Facebook/LinkedIn will strip query params when sharing)
    if (path.includes('?')) {
      path = path.split('?')[0];
    }
    
    // Remove trailing slash (except for root)
    path = path.replace(/\/+$/, '') || '/';
    
    console.log('[getPageMetadata] Requested path:', req.params.path, '→ Normalized:', path);
    
    // 2. Fetch SEO settings from database
    const row = await sequelize.query(
      'SELECT value FROM settings WHERE namespace = :ns',
      {
        type: QueryTypes.SELECT,
        replacements: { ns: 'seo' },
      }
    ) as any[];
    
    const seoSettings = row?.[0]?.value ?? DEFAULTS.seo;
    const existingPages = seoSettings.pages || [];

    console.log('[getPageMetadata] Found', existingPages.length, 'pages in settings');
    console.log('[getPageMetadata] Raw seoSettings:', JSON.stringify(seoSettings, null, 2));
    if (existingPages.length > 0) {
      console.log('[getPageMetadata] All pages:', JSON.stringify(existingPages.map((p: any) => ({ 
        path: p.path, 
        title: p.title?.substring(0, 30),
        enabled: p.enabled, 
        autoGenerated: p.autoGenerated 
      })), null, 2));
    } else {
      console.log('[getPageMetadata] WARNING: No pages found in settings!');
    }

    /**
     * Normalize slug in path to match frontend normalization
     * This ensures paths match even if they were stored with different formats
     */
    function normalizePathForComparison(pathToNormalize: string): string {
      if (!pathToNormalize) return '/';
      
      // Remove trailing slash (except for root)
      let normalized = pathToNormalize.replace(/\/+$/, '') || '/';
      
      // Extract slug from path (e.g., /posts/slug-name -> slug-name)
      const pathParts = normalized.split('/');
      if (pathParts.length >= 3) {
        // Has prefix and slug (e.g., /posts/slug-name)
        const prefix = pathParts.slice(0, -1).join('/'); // /posts
        const slug = pathParts[pathParts.length - 1]; // slug-name
        
        // Normalize slug
        let normalizedSlug = slug;
        try {
          normalizedSlug = decodeURIComponent(slug);
        } catch (e) {
          // If decode fails, use original slug
        }
        normalizedSlug = normalizedSlug
          .toLowerCase()
          .trim()
          .replace(/[^a-z0-9-]/g, '-') // Replace special chars with dash
          .replace(/-+/g, '-') // Replace multiple dashes with single dash
          .replace(/^-+|-+$/g, ''); // Remove leading/trailing dashes
        
        normalized = `${prefix}/${normalizedSlug}`;
      } else if (pathParts.length === 2 && pathParts[1]) {
        // Has slug only (e.g., /slug-name)
        const slug = pathParts[1];
        let normalizedSlug = slug;
        try {
          normalizedSlug = decodeURIComponent(slug);
        } catch (e) {
          // If decode fails, use original slug
        }
        normalizedSlug = normalizedSlug
          .toLowerCase()
          .trim()
          .replace(/[^a-z0-9-]/g, '-')
          .replace(/-+/g, '-')
          .replace(/^-+|-+$/g, '');
        normalized = `/${normalizedSlug}`;
      }
      
      return normalized || '/';
    }

    // 3. Try to find exact match first (normalize both paths for comparison)
    const normalizedRequestPath = normalizePathForComparison(path);
    console.log('[getPageMetadata] Normalized request path:', path, '→', normalizedRequestPath);
    
    let page = existingPages.find((p: any) => {
      if (!p.path) return false;
      
      // Normalize both paths for comparison
      const normalizedPagePath = normalizePathForComparison(p.path);
      
      // Check if paths match
      const matches = normalizedPagePath === normalizedRequestPath && p.enabled !== false;
      
      if (matches) {
        console.log('[getPageMetadata] Found exact match:', p.path, '→', normalizedPagePath, '===', normalizedRequestPath);
      }
      return matches;
    });

    // 4. If not found and it's home page, check if there's a page entry for '/'
    if (!page && (path === '/' || path === '')) {
      // Try to find a page entry for '/'
      const homePage = existingPages.find((p: any) => p.path === '/' && p.enabled !== false);
      if (homePage) {
        return res.json({
          title: homePage.title || 'Banyco',
          description: homePage.description || '',
          ogImage: homePage.ogImage || '',
          keywords: homePage.keywords || [],
        });
      }
      // No metadata found, return default
      return res.json({
        title: 'Banyco',
        description: '',
        ogImage: '',
        keywords: [],
      });
    }

    // 5. If found, return metadata
    if (page) {
      return res.json({
        title: page.title || '',
        description: page.description || '',
        ogImage: page.ogImage || '',
        keywords: page.keywords || [],
      });
    }

    // 6. Not found
    res.status(404).json({ error: 'Page metadata not found' });
  } catch (err) {
    console.error('[getPageMetadata] Error:', err);
    res.status(500).json({ error: 'Failed to load page metadata' });
  }
};

